### ISSUE TITLE
扫描过程中tscancode工具崩溃

### ISSUE THREAD

**Issue by kona8** [Tencent/TscanCode#34]
堆栈如下：
(gdb) bt
#0  0x00007f9e635712c7 in raise () from /usr/lib64/libc.so.6
#1  0x00007f9e635729b8 in abort () from /usr/lib64/libc.so.6
#2  0x00007f9e635b3e17 in __libc_message () from /usr/lib64/libc.so.6
#3  0x00007f9e635bc609 in _int_free () from /usr/lib64/libc.so.6
#4  0x000000000058c0b3 in Token::~Token() ()
#5  0x000000000058c238 in Token::deleteNext(unsigned long) ()
#6  0x0000000000598195 in Tokenizer::deleteInvalidTypedef(Token*) ()
#7  0x0000000000598289 in Tokenizer::simplifyTypedef2_eraseTypedefs(std::unordered_map<Token const*, STypedefEntry, std::hash<Token const*>, std::equal_to<Token const*>, std::allocator<std::pair<Token const* const, STypedefEntry> > >&) ()
#8  0x00000000005bbc38 in Tokenizer::simplifyTypedef2() ()
#9  0x00000000005c3adb in Tokenizer::simplifyTokenList1(char const*) ()
#10 0x00000000005cd809 in Tokenizer::tokenize(std::istream&, char const*, std::string const&, bool, bool) ()
#11 0x0000000000523014 in TscanCode::analyzeFile_internal(std::string const&, char const*, std::set<unsigned long long, std::less<unsigned long long>, std::allocator<unsigned long long> >&, bool&) ()
#12 0x0000000000523a0e in TscanCode::analyzeFile(std::istream&, std::string const&) ()
#13 0x00000000005243a6 in TscanCode::analyze(std::string const&) ()
#14 0x000000000040f5e2 in TscThreadExecutor::threadProc(void*) ()
#15 0x00007f9e6412fdd5 in start_thread () from /usr/lib64/libpthread.so.0
#16 0x00007f9e6363902d in clone () from /usr/lib64/libc.so.6
(gdb)

**Comment by kona8** [comment]
版本信息：TscanCodeV2.14.24.linux
